Fix call-id aging broken after switch to python3.
Make sure we use integer to do list slicing. Otherwise
exception below might happen:

Traceback (most recent call last):
  File "/usr/local/lib/rtp_cluster/sippy_lite/Core/EventDispatcher.py", line 179, in dispatchTimers
    el.cb_func(*el.cb_params)
  File "/usr/local/lib/rtp_cluster/Rtp_cluster_member.py", line 146, in call_id_map_aging
    self.call_id_map_old = self.call_id_map[len(self.call_id_map) / 2:]
TypeError: slice indices must be integers or None or have an __index__ method

TT:	SS-5592